add functionality to only turn on maintenance mode for search section…
apostrophecms/apostrophe-maintenance-mode pull request #2
Opened 2018-11-13 21:34 UTC by woodbrearlham

…s of the site

2018-11-15 13:06 UTC, boutell requested changes
hi Brad, see my feedback. Thanks for contributing.

2018-11-15 13:06 UTC, boutell commented on README.md
> +Add a list of pages '/about' this will only add the maintence mode for any page that their url contains the listed url
I was thinking you'd do a prefix match here, specifically either an exact match or "followed by a slash" match, so you can lock down whole directories easily... otherwise your original idea of picking pages probably makes more sense. Maybe a boolean to choose between exact match and "directory" match.

2018-11-15 13:06 UTC, boutell commented on index.js
> +      self.included = includeList.map( function(obj) { return obj.page; } );
Please format consistently with existing code.

2018-11-15 13:06 UTC, boutell commented on index.js
> +      const includeList = req.data.global.pagelist;
Use the same prefix as the other fields to avoid conflicts with project level fields that could exist. Be consistent about the capitalization pattern.

2018-11-15 13:06 UTC, boutell commented on index.js
> +      if(includeList.length){
Format consistently:

`if (includeList.length) {`

2018-11-15 13:06 UTC, boutell commented on index.js
> +        console.log(_.includes(includeList.page, url));
Remove console test calls before submitting PRs.

2018-11-15 13:06 UTC, boutell commented on index.js
> +        if (_.includes(self.included, url)){
Format consistently (space before `{`)

2018-11-15 13:06 UTC, boutell commented on index.js
> +            return res.status(503).send(self.render(req, 'message', {
Better to factor this out to a function so both branches can call it without duplication and possible bugs later if only one changes.

2018-11-15 13:06 UTC, boutell commented on index.js
> +      const includeList = req.data.global.pagelist;
Make sure `req.data.global` exists before touching it.

2018-11-15 13:06 UTC, boutell commented on lib/modules/apostrophe-maintenance-mode-global/index.js
> +        fields: [ 'maintenanceMode',,'pagelist','maintenanceTitle', 'maintenanceMessage' ]
Duplicate comma. Format consistently, spaces after commas.

2018-11-15 13:11 UTC, woodbrearlham commented on README.md
> +Add a list of pages '/about' this will only add the maintence mode for any page that their url contains the listed url
I was just trying to make it simple where it checks to see if string is included in the url. If you only want a single page way down the line then define the /page/child/grand-child would look for that entire string of url to exist.

2018-11-15 14:17 UTC, woodbrearlham commented
I've cleaned up the code thanks for the feedback

2018-11-16 14:32 UTC, boutell commented on index.js
> +          return res.status(503).send(self.render(req, 'message', {
Factor this out to a function and call it from both places.

2018-11-16 14:32 UTC, boutell commented on index.js
> +          return res.status(503).send(self.render(req, 'message', {
I'm talking about the code that sends the response. DRY (Don't Repeat Yourself).

2018-11-16 14:32 UTC, boutell commented on index.js
> +          return next();
I believe you broke the regular use case for the module with this line.

2018-11-16 14:32 UTC, boutell commented on index.js
> +        if (self.onlySelected.length && _.includes(self.onlySelected, url)) {
Making people paste their own URLs and yet not doing prefix matches is a little underwhelming, it would be great to match anything after an `*`. I don't think we need full regular expressions, just a simple wildcard.

2018-11-19 16:07 UTC, boutell approved these changes

2018-11-19 16:08 UTC, boutell requested changes
As written looks like it would still break the existing use case, see comments inline. Also I think it makes sense to add the support for a single * wildcard at the end.

2020-05-12 20:22 UTC, abea commented
Closing for inactivity.

2020-05-12 20:22 UTC, closed without merging